version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Installing app dependencies...
      - npm install
  build:
    commands:
      - echo Building static site...
      - npm run-script build
  post_build:
    commands:
      - echo entering into post build phase...
# Moves artifacts from build folder to S3
artifacts:
  files:
    - '**/*'
  base-directory: 'build'
